[features]
seeds = false
[programs.localnet]
es_token_metadata = "4cPZHiknrGUbDadU8n15D3GpvDfw1GbcvGoT3ccSg529"

[programs.devnet]
es_token_metadata = "4cPZHiknrGUbDadU8n15D3GpvDfw1GbcvGoT3ccSg529"
gay_dungeon = "Bz4repUbACRtNKsrTZUhgfNzXKbsu6JcLzawHFqoSz3X"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

gay-build = "anchor build --program-name gay_dungeon"
gay-deploy-w-idl = "anchor build --program-name gay_dungeon && anchor deploy --program-name gay_dungeon && anchor idl upgrade --filepath target/idl/gay_dungeon.json Bz4repUbACRtNKsrTZUhgfNzXKbsu6JcLzawHFqoSz3X"
gay-get-idl = "anchor idl fetch Bz4repUbACRtNKsrTZUhgfNzXKbsu6JcLzawHFqoSz3X"