[features]
seeds = false
[programs.localnet]
es_token_metadata = "4cPZHiknrGUbDadU8n15D3GpvDfw1GbcvGoT3ccSg522"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ikkyu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
