[features]
seeds = false
[programs.localnet]
es_token_metadata = "4cPZHiknrGUbDadU8n15D3GpvDfw1GbcvGoT3ccSg522"

[programs.devnet]
es_token_metadata = "2omaJbwJ1n2sxKu66UXtKdQ179UaxtFKZuKXqer5jaBX"
gay_dungeon = "Bz4repUbACRtNKsrTZUhgfNzXKbsu6JcLzawHFqoSz3X"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

gay-build = "anchor build --program-name gay_dungeon"
gay-deploy-w-idl = "anchor build --program-name gay-dungeon && anchor deploy --program-name gay-dungeon && anchor idl upgrade --filepath target/idl/gay_dungeon.json Bz4repUbACRtNKsrTZUhgfNzXKbsu6JcLzawHFqoSz3X"
gay-get-idl = "anchor idl fetch Bz4repUbACRtNKsrTZUhgfNzXKbsu6JcLzawHFqoSz3X"
gay-upgrade-idl = "anchor idl upgrade --filepath target/idl/gay_dungeon.json Bz4repUbACRtNKsrTZUhgfNzXKbsu6JcLzawHFqoSz3X"
build-es = "anchor build -p es_token_metadata"
deploy-es = "anchor deploy -p es_token_metadata"
test-es = "anchor run build-es && anchor run deploy-es && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/es-token-metadata/es-token-metadata.ts"
get-idl-es = "anchor idl fetch 4fhHqbNqYXmGVgYtff1y75BGczADSq3vB9nNnzfDRNwi"